development: &development
  gateway_url: "https://external.development.carecloud.com"
  backend_url: "https://external.development.carecloud.com"
  ngrok_url:   "http://791b33a7.ngrok.com"
  cors_url:    "http://developer.development.carecloud.com"
  platform_url: "https://platform.development.carecloud.com"

test:
  <<: *development

qa: 
  gateway_url: "https://external-api-gateway.qa.carecloud.com"
  backend_url: "https://external-api-elb-qa.carecloud.com"
  cors_url:    "http://developer.development.carecloud.com"
  platform_url: "https://platform.qa.carecloud.com"

staging: 
  gateway_url: "https://api-staging.carecloud.com"
  backend_url: "https://api-pub-stg.carecloud.com"
  cors_url:    "http://developer.development.carecloud.com"
  platform_url: "https://platform-staging.carecloud.com"
  
demo: 
  gateway_url: "https://api.careclouddemo.com"
  backend_url: "https://api.careclouddemo.com"
  cors_url:    "http://developer.carecloud.com"
  platform_url: "https://platform.careclouddemo.com"

production: 
  gateway_url: "https://api.carecloud.com"
  backend_url: "https://api-atf0c1d2.carecloud.com"
  cors_url:    "http://developer.carecloud.com"
  platform_url: "https://platform.carecloud.com"
